trigger:
 branches:
   include:
     - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-user'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-user'
    cmd: 'oc new-project dotnet-app'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-user'
    cmd: 'oc delete all --all -n dotnet-app'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-user'
    cmd: 'oc new-app dotnet:2.1-ubi8~https://github.com/sa-ne/rhel-edge  --context-dir=app -l app=demo --name=demo'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-user'
    cmd: 'oc create -f ${SYSTEM_DEFAULTWORKINGDIRECTORY}/resources/demo-app-service-monitor.yaml'
    ignoreFlag: true