- name: Enable SEBoolean container_manage_cgroup
  seboolean:
    name: container_manage_cgroup
    persistent: yes
    state: yes

- name: Pull PCP Container
  containers.podman.podman_image:
    name: "{{ image_registry }}/{{ image_namespace }}/{{ image_name }}"
    pull: true
    state: present
    username: "{{ image_registry_username }}"
    password: "{{ image_registry_password }}"

- name: Copy PCP Container systemd Unit File
  copy:
    src: files/container-pcp.service
    dest: /etc/systemd/system/container-pcp.service
    owner: root
    group: root
    mode: 0644
    setype: systemd_unit_file_t

- name: Enable container-pcp Service
  systemd:
    name: container-pcp
    state: started
    enabled: yes

- name: Enable PCP Ports in Firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - 44323
    - 44322
    - 44321