apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    endpoint: edge
  name: edge-service-monitor
  namespace: edge-rhel-endpoints
spec:
  endpoints:
  - interval: 10s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      endpoint: edge