---
# vars file for podman-pull-and-run-image
# Image registry_vars
image_registry: "{{ tower_secret_image_registry | default('quay.io') }}"
image_registry_username: "{{ tower_secret_image_registry_username | default('admin') }}"
image_registry_password: "{{ tower_secret_image_registry_password }}"

# Image Vars
image_namespace: "{{ tower_input_image_namespace | default('quay.io') }}"
image_name: "{{ tower_input_image_name | default('place-holder') }}"
image_tag: "{{ tower_input_image_tag | default('latest') }}"

# Container Vars
container_name: "{{ tower_input_container_name | default('placeholder') }}"
container_privileged: "{{ tower_input_container_privileged | default(false) }}"
container_restart_policy: "{{ tower_input_container_restart_policy | default('always') }}"
