---
# tasks file for podman-pull-and-run-image
#collection containers.podman required
- name: pull down the {{ image_namespace }}/{{ image_name }}:{{ image_tag }} image from {{ image_registry }}
  containers.podman.podman_image:
    name: "{{ image_registry }}/{{ image_namespace }}/{{ image_name }}"
    tag: "{{ image_tag }}"
    pull: true
    state: present
    validate_certs: false
    username: "{{ image_registry_username }}"
    password: "{{ image_registry_password }}"

- name: Create a {{ container_name }} container running the {{ image_namespace }}/{{ image_name }}:{{ image_tag }} image
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    restart_policy: "{{ container_restart_policy }}"
    privileged: "{{ container_privileged }}"
    ports:
    - "8080:8080"