---
# tasks file for podman-stop-and-remove-image
#collection containers.podman required
- name: Stop the {{ container_name }} container 
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: absent

- name: remove the {{ image_namespace }}/{{ image_name }}:{{ image_tag }} image 
  containers.podman.podman_image:
    name: "{{ image_namespace }}/{{ image_name }}"
    tag: "{{ image_tag }}"
    state: absent
